### PR TITLE
Splitting tests, addresses #24. Plus a pep8 issue in cmd.py

### PR DESCRIPTION
**Pull request by itsbenweeks**
This addresses #24, creating a separate test library for actions.

### CODE REVIEW

**Comment by carsongee** [comment]
It appears to have merge conflicts, also, if you change the commit to have one of the magic words it will automagically close the request when merged: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by itsbenweeks** [comment]
Huh. Rebasing brought a merged commit up? Strange.

**Comment by itsbenweeks** [comment]
Looks like my old test isn't covering my previous commit. I'll have to look at this sometime tomorrow, then.

**Comment by itsbenweeks** [comment]
Ooops. I had reset to the old tests, just fixed that now.

**Comment by carsongee** [comment]
Cool, looks great :v:

**Pull request merged**
